android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

closing #107 
as correctly stated by @jonasanker updating the gradle version fixed the warnings related to 'mapping new ns (...) to old ns (...)'

bump gradle version to 7.3

---

lib/utils/responsive.dart
lib/widgets/components/card.dart
lib/widgets/components/helpers/grid.dart
pubspec.yaml

closes #121 
based on grid implementation from #122 
Cards have been adjusted slightly to play nicely with parent widgets that allows them to render at their intrinsic size.
All cards, except for `ReceiptCard`, should always sit in either a `Column` or a `Grid`.
`ReceiptCard` should sit in a similar widget that would allow it to display its "natural" size, such as `IntrinsicHeight` or `UnconstrainedBox`.
- Add `Grid` widget
- Adjust `CardBase`
- Add `flutter_layout_grid` package
- Add `deviceIsSmall` function in `lib/utils/responsive.dart`

Add `Grid` widget

---

pubspec.lock
pubspec.yaml

The new version of [swagger-dart-code-generator](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator) is broken -- code can't be generated (on Windows, at least)
See issue https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/346
We roll back to the previous version

Hotfix: Downgrade code generator version

---

lib/widgets/components/entry/register/register_continue_button.dart
lib/widgets/components/entry/register/register_email_body.dart
lib/widgets/components/entry/register/register_name_body.dart
lib/widgets/components/entry/register/register_passcode_body.dart
lib/widgets/components/rounded_button.dart
lib/widgets/pages/register/register_email_page.dart
lib/widgets/pages/register/register_name_page.dart
lib/widgets/pages/register/register_passcode_page.dart

* each section of the register flow has a continue button that acts in accordance with already defined behavior regarding errors
* rounded_button now hides splash effect when disabled
closes #93

Add continue buttons to register flow pages

---

lib/widgets/components/receipt/receipt_card.dart

closes #183 
The data objects still contain their UTC time, but the local time is displayed. Would it be preferred to save the local time in the objects instead? Thoughts?

Receipts displays local time

---

lib/widgets/analog_logo.dart
lib/widgets/components/entry/login/login_numpad.dart
lib/widgets/pages/login/login_page.dart
lib/widgets/pages/register/register_page.dart

Resolves #178
No page in login or register flow should overflow.
- Analog logo becomes smaller based on screen width
- Numpad becomes smaller based on screen width
- Numpad paddings adjusted
- Login pages no longer vertically centered (now matches design spec)
- Login page padding from top based on screen width
- All login and register pages made scrollable as a last resort
Future:
- Consider removing overscroll or replace it with bouncing (design desicion)

Entry flow is responsive

---

lib/base/style/theme.dart
lib/widgets/components/scaffold.dart

Fix #56 
Added appBarTheme into `theme.dart`, with centerTile=false, alongside moving the default elevation value from `scaffold.dart` into the appBarTheme as well.

Resolve #56 (Left-align appBar title on iOS)

---

lib/cubits/authentication/authentication_cubit.dart
lib/cubits/receipt/receipt_cubit.dart
lib/cubits/tickets/tickets_cubit.dart
lib/service_locator.dart
lib/widgets/components/purchase/purchase_overlay.dart
lib/widgets/components/tickets/swipe_ticket_confirm.dart
lib/widgets/pages/home_page.dart

Fixes a bug with that redundantly runs the initial cubit method listed in home_page.dart and removes the need to reset cubits on logout

Move cubits out of service locator

---

lib/widgets/components/receipt/receipts_list_view.dart
lib/widgets/pages/home_page.dart
lib/widgets/pages/receipts/receipts_page.dart
lib/widgets/pages/settings/settings_page.dart
lib/widgets/pages/stats_page.dart
lib/widgets/pages/tickets/tickets_page.dart
lib/widgets/routers/app_flow.dart

Fix #257
New navigation bar behaviour:
- Pressing the nav bar icon of a flow that is not currently active will bring the user to the page they were on before if any; otherwise default
- (This was the old behaviour for all cases.)
- Pressing the nav bar icon of the flow that is currently active will bring the user back to the default page and scroll that page to the top.

Reset nav bar app flows when tapping nav bar icon

---

lib/widgets/pages/home_page.dart

Fix #267
Moved _bottomNavAppFlows into the _HomePageState class.
Before it was outside the class (in the outermost level) in home_page.dart.
This resulted in the app sometimes trying to display a stale AppFlow widget that had been dismounted (after logging out).

Fix #267 (Logging out and in breaks app)

---

lib/cubits/statistics/statistics_cubit.dart
lib/cubits/statistics/statistics_state.dart
lib/cubits/user/user_cubit.dart
lib/cubits/user/user_state.dart
lib/widgets/components/tickets/tickets_section.dart
lib/widgets/pages/stats_page.dart

Fix #249
fix~ #248 (see note)
Currently, after updating user info, the user object returned by the backend gives the incorrect rank info. for the user.
We work around this bug by fetching user info an extra time after the user changes user info.

Update leaderboard after swiping ticket and after changing user info

---

lib/widgets/components/list_entry.dart
lib/widgets/components/receipt/receipt_list_entry.dart
lib/widgets/components/settings_list_entry.dart
lib/widgets/components/stats/leaderboard_entry.dart
lib/widgets/pages/settings/settings_page.dart

Fix #280 
Fully fixes any `ListEntry` jank once and for all (hopefully).
Before, all list entries had the left side widget wrapped in a `Flexible` widget.
This caused a problem with SettingsListEntry, because here, the "variable"-sized widget (e.g. user email text) was on the right side.
The previous solution for that problem was to place the right side widget in a fixed size constrained box, but that fix still doesn't play well with variable length emails.
The proposed solution introduces `sideToExpand` inside of `ListEntry`. It tells the ListEntry which side should be displayed
in full, and which side should be wrapped in a `Flexible` widget (which allows that side to reduce in size based on remaining space).
Used correct `SettingDescription` widget for the right side of each …

Add variable flexibility of `ListEntry`

---

lib/widgets/pages/home_page.dart

Fix #283
Keep track of what navigation bar flows the user has visited since last visiting the default nav bar flow (Tickets).
Intercept the Android back button at the root of every navigation flow, and send the user to the previously visited nav bar flow, if present.
If the user is at the Tickets flow and presses back button, exit the app.

Manage a stack of visited navigation bar flows

---

lib/cubits/authentication/authentication_cubit.dart
lib/cubits/login/login_cubit.dart
lib/cubits/register/register_cubit.dart
lib/cubits/user/user_cubit.dart
lib/data/repositories/shared/account_repository.dart
lib/data/storage/secure_storage.dart
lib/models/account/update_user.dart
lib/utils/encode_passcode.dart
lib/utils/reactivation_authenticator.dart

Move encoding responsibility out of account_repository;
Now all its methods expects already encoded passcodes.
Variable and method names for passcodes appropriately named `encodedPasscode` if they expect to be encoded.
Moved encode function to `utils/encode_passcode.dart`
---
Addresses
"TODO: Should probably have another return type in order to support
the intended registration flow?"
in `lib\data\repositories\shared\account_repository.dart`

feat: save encoded passcode in secure storage

---

lib/widgets/pages/settings/credits_page.dart

Built in page by Flutter to show all package licenses, including our own (under package coffeecard)

Add license page

---

android/app/build.gradle
lib/payment/mobilepay_service.dart
pubspec.lock
pubspec.yaml

Fix #350 
Rolled back swagger_dart_code_generator to 2.6.0
Also bumped the compile sdk for android to version 33 since that is a requirement of the latest secure storage flutter package that we are also using

Rolled back swagger_dart_code_generator to 2.6.0

---

lib/widgets/components/stats/stat_card.dart
lib/widgets/components/stats/stats_section.dart

closes #357 
When the user has ro rank, instead of displaying "0th" on the statistics page, a dash '-' will now be displayed instead.

Placeholder for statistics page when user is unranked

---

lib/utils/time_since.dart
test/utils/time_since_test.dart

When time is less than 2 minutes ahead of currentTime, do not display "in the future".
Currently, swipe receipt can display "in the future" because of time differences of a few milliseconds.

Fix "In the future" when diff is very small

---

makefile

Useful when font doesn't show properly in emulator/simulator, or when an unexpected build error occurs locally

misc: add `make clean` command

---

lib/widgets/components/tickets/opening_hours_indicator.dart

With the old code, if the state was an error, the opening status would default to open.

Fix for OpeningHoursIndicator, so it now behaves as expected on errors

---

lib/cubits/form/form_bloc.dart

A fix for the error reported by @marfavi 
Testing has been minimal due to working from the train, but it appears to work as intended on my phone

Fixing error in validation logic of form_bloc

---

.github/workflows/release.yml

Included release.yml to the list of paths that should trigger a release
https://github.com/AnalogIO/coffeecard_app/commit/7702fde49fc514fe1da8c05303bcd7af1726bea5 didn't trigger a release workflow (which we need right now), but turns out the list of paths to trigger the workflow might have been incorrect.

Trigger release workflow on workflow change

---

lib/base/strings.dart
lib/core/errors/failures.dart
test/core/network/network_request_executor_test.dart

Closes #447 
Closes #450
ServerFailure returns an unknown error occured, if unable to decode response as json

ServerFailure returns an unknown error occured

---

lib/core/extensions/string_extensions.dart
lib/features/opening_hours/data/repositories/opening_hours_repository_impl.dart
lib/features/purchase/domain/entities/payment_status.dart
lib/features/purchase/presentation/pages/buy_tickets_page.dart
lib/features/receipt/data/models/purchase_receipt_model.dart
lib/features/receipt/data/repositories/receipt_repository_impl.dart
lib/features/receipt/domain/entities/purchase_receipt.dart
lib/features/receipt/domain/entities/receipt.dart
lib/features/receipt/presentation/pages/view_receipt_page.dart
lib/features/receipt/presentation/widgets/list_entry/placeholder_receipt_list_entry.dart
lib/features/receipt/presentation/widgets/list_entry/purchase_receipt_list_entry.dart
lib/features/receipt/presentation/widgets/list_entry/receipt_list_entry.dart
lib/features/receipt/presentation/widgets/list_entry/swipe_receipt_list_entry.dart
lib/features/receipt/presentation/widgets/receipt_card.dart
lib/features/receipt/presentation/widgets/receipt_overlay.dart
lib/features/ticket/presentation/widgets/tickets_section.dart
test/features/receipt/data/repositories/receipt_repository_impl_test.dart

show status on receipts

---

lib/features/ticket/data/datasources/ticket_remote_data_source.dart
lib/features/ticket/presentation/widgets/swipe_ticket_confirm.dart
lib/features/ticket/presentation/widgets/tickets_section.dart
test/features/ticket/data/datasources/ticket_remote_data_source_test.dart

`CoffeeCard`s are now grouped by id instead of name; if a group has tickets with different names, their names will be joined
Closes #466

fix(tickets): Fix multiple `CoffeeCard`s sharing the same product id

---

lib/features/receipt/data/datasources/receipt_remote_data_source.dart

fix: Remove null type cast in `receipt_remote_data_source.dart`

---

lib/base/strings.dart
lib/features/purchase/domain/entities/payment_status.dart
lib/features/purchase/presentation/pages/buy_tickets_page.dart
lib/features/receipt/presentation/pages/view_receipt_page.dart
lib/features/receipt/presentation/widgets/list_entry/placeholder_receipt_list_entry.dart
lib/features/receipt/presentation/widgets/list_entry/purchase_receipt_list_entry.dart
lib/features/receipt/presentation/widgets/list_entry/receipt_list_entry.dart
lib/features/receipt/presentation/widgets/list_entry/swipe_receipt_list_entry.dart
lib/features/receipt/presentation/widgets/receipt_card.dart
lib/features/receipt/presentation/widgets/receipt_overlay.dart
lib/features/ticket/presentation/widgets/tickets_section.dart

Closes #477.
- `PurchaseReceiptListEntry` widget now has 'tappable' set to false, disabling purchase receipts.
- Timestamp has been added below the purchase/swipe status in `ReceiptListEntry`.
- Updated `PaymentStatus` string values to provide clearer descriptions.
- Renamed 'purchaseStatus' field to 'status' across multiple generic receipt widgets.
- Refactored `PurchaseReceiptListEntry` to show price differently (or hide it), based on status.
- misc: Updated `_formatter` to `_formatDate`/`_formatDateTime` in `ReceiptListEntry` and `ReceiptCard`.
- misc: Removed rounded edges from `ReceiptListEntry`.

fix(receipts): Remove purchase receipt view & refactor payment status display

---

lib/core/widgets/pages/splash/splash_loading_page.dart

Add loading indicator to splash page after duration

---

lib/core/external/screen_brightness.dart
lib/core/network/network_request_executor_mapping.dart
lib/core/strings.dart
lib/core/widgets/components/loading_overlay.dart
lib/core/widgets/pages/splash/splash_error_page.dart
lib/features/login/presentation/pages/login_page_passcode.dart
lib/features/login/presentation/widgets/forgot_passcode_form.dart
lib/features/product/presentation/pages/buy_tickets_page.dart
lib/features/receipt/presentation/widgets/receipt_overlay.dart
lib/features/register/presentation/pages/register_page_name.dart
lib/features/register/presentation/widgets/forms/register_name_form.dart
lib/features/ticket/presentation/widgets/tickets_section.dart
lib/features/voucher/presentation/pages/redeem_voucher_page.dart
lib/service_locator.dart

Consolidate receipt_overlay and loading_overlay

---

lib/core/widgets/pages/splash/splash_loading_page.dart

Splash loading indicator throws an exception if the timer expires and the widget is not mounted

Fix widget emitting state after close

---

lib/features/login/presentation/widgets/forgot_passcode_form.dart

Inverted an if-else that would determine whether to show the "no account exists" error or not.
Fix #520

Fix email validation logic in Forgot Passcode page

---

.github/workflows/release-dev.yml

Note: the [prod version](https://github.com/AnalogIO/coffeecard_app/blob/main/.github/workflows/release-prod.yml) does not look like it needs any update. If I am mistaken, please correct this PR

Fix Android appbundle artifact name

---

lib/core/external/date_service.dart
lib/features/opening_hours/data/datasources/opening_hours_local_data_source.dart
lib/features/opening_hours/data/repositories/opening_hours_repository_impl.dart
lib/features/opening_hours/domain/entities/opening_hours.dart
lib/features/opening_hours/domain/entities/timeslot.dart
lib/features/opening_hours/presentation/cubit/opening_hours_cubit.dart
lib/features/opening_hours/presentation/cubit/opening_hours_state.dart
lib/features/opening_hours/presentation/pages/opening_hours_page.dart
test/features/opening_hours/data/repositories/opening_hours_repository_impl_test.dart
test/features/opening_hours/domain/usecases/get_opening_hours_test.dart
test/features/opening_hours/presentation/cubit/opening_hours_cubit_test.dart

Uses the flutter-native TimeOfDay class, which has localized time formatting.
This has been extended with comparison methods <= and isInTimeslot.
Timeslot class simplifies with this change.
Simplify DateService to only contain one getter.
Make sure of fpdart's Option instead of null values. Use None for closed days.
Clean up tests and use NiceMocks for mocking.

refactor: Option type and TimeOfDay in opening hours

---

.github/actions/build_android/action.yml
.github/workflows/build.yml
.github/workflows/release-dev.yml
.github/workflows/release-prod.yml

When removing debug signing as done in #542 apk builds from firebase fails to install. This PR ensures both Appbundles and APKs are signed

Sign apk builds

---

lib/core/styles/app_text_styles.dart
lib/core/widgets/components/rounded_button.dart
lib/core/widgets/pages/splash/splash_error_page.dart
lib/features/login/presentation/pages/login_page_passcode.dart

This commit reduces code duplication by creating a new constructor to the
`RoundedButton` class, making it usable as a replacement for the following buttons:
1. the "Resend verification email" button
2. the button in `SplashErrorPage`
Beforehand, these two buttons used tedious boilerplate by invoking the Material `ElevatedButton`; a thing the `RoundedButton` was supposed to eliminate.
Additionally, I simplified some code in the files this change affected.

refactor(ui): add RoundedButton.bright constructor

---

.github/actions/build_android/action.yml
.github/actions/build_ios/action.yml
.github/actions/setup_flutter_environment/action.yml
.github/actions/verify_build_type/action.yml
.github/workflows/build.yml
.github/workflows/release-dev.yml
.github/workflows/release-prod.yml
.github/workflows/test.yml

This PR fixes the release pipeline bug that caused building a development version for release (in the first commit), and increases code robustness to prevent the same bug from appearing again (in the second commit).
The error was caused by a bug in actions code, which passed an ill-defined input variable (whether to build a dev/prod app) to another action. The input variable expected by the second action was optional, defaulting to build a dev version if no input variable is present.
---
Build configurations across Android and iOS build pipelines were updated to enforce the specification of 'development' or 'production' as mandatory build types. Introduced a shared 'verify_build_type' action that validates this input. This change ensures that artifacts are built against the correct …

fix(ci): development version built in release pipeline

---

.github/actions/build_ios/action.yml

this PR will change the build_ios action to always install certificates and provisioning profiles, instead of only doing so for development builds.

fix(ci): apple certs not installed on prod

---

.github/workflows/README.md
.github/workflows/release-dev.yml

Closes #549
Replaced the deprecated `FIREBASE_TOKEN` with `FIREBASE_SERVICE_ACCOUNT_JSON` in the release-dev workflow to follow updated Firebase Distribution requirements. This change aligns with best practices and prepares for future Firebase Action updates.
Also streamlined the README documentation for GitHub Actions secrets by reformatting the table into a list with improved headings. This enhances readability, especially when editing the file, as whitespace are now removed.

chore(ci): migrate to firebase service account

---

.github/actions/build_android/action.yml
.github/actions/setup_flutter_environment/action.yml

Reference: https://github.com/r0adkll/sign-android-release/issues/84#issuecomment-1889636075

Set buildtools variable used for android App signing

---

lib/core/strings.dart
lib/features/ticket/presentation/cubit/tickets_cubit.dart
lib/features/ticket/presentation/cubit/tickets_state.dart
lib/features/ticket/presentation/pages/tickets_page.dart
lib/features/voucher/presentation/pages/redeem_voucher_page.dart
test/features/ticket/presentation/cubit/tickets_cubit_test.dart

1. always refresh user's tickets after purchase attempt
2. show a more open-ended error message if the purchase was cancelled/rejected to urge double-checking on user's end
3. enable pull to refresh on the Tickets page

feat(purchase): add guardrails for failed purchases

---

lib/core/widgets/components/dialog.dart

On iOS the background color of dialogs are ignored when calling `showAdaptiveDialog`. Instead, calling `showDialog` creates a Material dialog which enforces the background/"barrier" color.

fix(dialog): background color of dialogs

---

lib/core/strings.dart
lib/core/widgets/components/dialog.dart
lib/features/product/presentation/functions.dart
lib/features/product/presentation/widgets/buy_ticket_bottom_modal_sheet.dart
lib/features/product/product_model.dart
lib/features/ticket/domain/entities/ticket.dart
lib/features/ticket/domain/usecases/load_tickets.dart
lib/features/ticket/presentation/widgets/perk_card.dart
lib/features/ticket/presentation/widgets/swipe_ticket_confirm.dart
lib/features/ticket/presentation/widgets/tickets_section.dart

Closes #582 
This introduces a drop down on free perks with multiple menu items, allowing the user to select which item they are claiming. This is to give better tracking of the menu items being "purchased", even with premium perks, and to lessen confusion by baristas as the default receipt just says "Espresso".

feat(tickets): add menu item selection for free premium perk

---

lib/features/product/presentation/cubit/product_state.dart

Attempting to claim perks in the "Buy single drink" page currently causes an error. Since these perks should only be shown on the home page anyways, they have been removed from the "Buy single drink" page.

fix(purchase): hide perks products in "buy single drink" page

---

lib/core/widgets/pages/home_page.dart
lib/core/widgets/routers/app_flow.dart

fix(ui, android): back button exits app; navBar tap scrolling and going back at the same time
