.github/workflows/flutter.yml, lib/base/style/fonts.dart
- Build codebase
- Run unit tests
=> Setup Github Actions Continuous Integration

lib/base/strings.dart, lib/base/style/colors.dart, lib/base/style/text_styles.dart, lib/base/style/theme.dart, lib/main.dart, lib/widgets/pages/home_page.dart, lib/widgets/pages/receipts_page.dart, lib/widgets/pages/settings_page.dart, lib/widgets/pages/stats_page.dart, lib/widgets/pages/tickets_page.dart, test/widget_test.dart
Applied our colours to the Scaffold/MaterialApp.
Added pages & a way to navigate through them. (Only the Tickets page have content, but they all have their own title, seen in the app bar).
=> Apply theming & add bottom navigation bar

lib/main.dart, lib/service_locator.dart, pubspec.yaml
- GetIt package added to dependencies
- Services are configured at startup
=> Dependency Injection using GetIt

lib/widgets/components/entry/login/login_email_text_field.dart
Don't hide the keyboard when submitting via the keyboard action button
Resolves #17
=> Don't hide the keyboard on login page

build.yaml, lib/data/repositories/account_repository.dart, lib/data/repositories/app_config_repository.dart, openapi/coffeecard_api.swagger.json
=> Update Api to latest OpenApi spec

openapi/coffeecard_api.swagger.json
=> Update OpenApi spec with latest API changes

pubspec.yaml
=> bump versions and depend on concrete version

lib/cubits/analog_closed_popup/cubit/analog_closed_popup_cubit.dart, lib/data/api/coffee_card_api_constants.dart, lib/data/repositories/shiftplanning/opening_hours_repository.dart, lib/service_locator.dart, openapi/shiftplanning_api.swagger.json
=> fetch analog open from shifty

android/app/build.gradle, android/app/src/main/AndroidManifest.xml
=> update android embedding

lib/widgets/components/coffee_card.dart, lib/widgets/components/slide_button.dart
=> fix slide button

lib/base/strings.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/pages/settings/your_profile_page.dart
To complete PR #109 that was merged too early
=> Move strings from settings pages to `strings.dart`

android/app/src/main/AndroidManifest.xml, ios/Runner/Info.plist, pubspec.yaml
=> Rename app to "Analog"

lib/base/strings.dart, lib/cubits/login/login_cubit.dart, lib/cubits/receipt/receipt_cubit.dart, lib/cubits/receipt/receipt_state.dart, lib/data/repositories/shiftplanning/opening_hours_repository.dart, lib/data/repositories/v1/account_repository.dart, lib/data/repositories/v1/app_config_repository.dart, lib/data/repositories/v1/coffeecard_repository.dart, lib/data/repositories/v1/product_repository.dart, lib/data/repositories/v1/receipt_repository.dart, lib/data/repositories/v1/ticket_repository.dart, lib/data/repositories/v2/purchase_repository.dart, lib/widgets/components/analog_closed_popup.dart, lib/widgets/components/coffee_card.dart, lib/widgets/components/entry/login/login_email_text_field.dart, lib/widgets/components/entry/login/login_title.dart, lib/widgets/components/receipt/receipt_overlay.dart, lib/widgets/components/single_coffee_card.dart, lib/widgets/components/slide_button.dart, lib/widgets/components/tickets_section.dart, lib/widgets/pages/buy_tickets_page.dart, lib/widgets/pages/login/login_email_page.dart, lib/widgets/pages/login/login_passcode_page.dart, lib/widgets/pages/receipts/receipts_page.dart, lib/widgets/pages/tickets_page.dart, lib/widgets/routers/receipts_flow.dart, lib/widgets/routers/register_flow.dart, lib/widgets/routers/settings_flow.dart
=> move strings to base/strings.dart

lib/cubits/register/register_cubit.dart, lib/utils/email_utils.dart, lib/widgets/components/entry/register/register_email_text_field.dart
Title says it all 
Closes #126
=> Bugfix: Added ".trim()" to ignore whitespaces with email registration

lib/base/strings.dart, lib/data/repositories/v1/receipt_repository.dart, lib/models/receipts/receipt.dart, lib/utils/time_since.dart, lib/widgets/components/receipt/receipt_list_entry.dart, lib/widgets/components/receipt/receipts_list_view.dart, lib/widgets/pages/receipts/view_receipt_page.dart
Added message to receipt page when no receipts exist. Fixed the ordering of receipts, since someone had reversed it. ReceiptListEntry now takes a receipt as argument instead
Closes #74 
Closes #73
=> Polishing the receipts page

lib/base/strings.dart, lib/base/style/text_styles.dart, lib/widgets/pages/settings/settings_page.dart
closes #139 
- UserID added to settings page
- Some textstyles were updated according to design.
=> User ID displayed in settings

lib/cubits/environment/environment_cubit.dart, lib/cubits/environment/environment_state.dart, lib/widgets/components/receipt/receipt_card.dart, lib/widgets/components/receipt/receipt_overlay.dart, lib/widgets/components/scaffold.dart, lib/widgets/pages/receipts/view_receipt_page.dart, lib/widgets/routers/splash_router.dart
small write up to demonstrate how the environment state would look like if it was a state class instead of an enum
unknown state has been replaced by EnvironmentInitial/EnvironmentError classes that have to be checked
personally i think either implementation looks OK and merging this branch should be optional
=> suggested change to Environment warning

lib/base/strings.dart, lib/cubits/user/user_cubit.dart, lib/cubits/user/user_state.dart, lib/data/repositories/v1/account_repository.dart, lib/widgets/components/loading.dart, lib/widgets/components/settings_group.dart, lib/widgets/components/user_card.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/pages/settings/your_profile_page.dart
moved location of setting to the Your Profile view
added loading indicator when toggling between on/off
text of setting changed to "Appear anonymous in leaderboard" (or "Appear anonymous" on iPhone 5-sized screens)
added description for setting group
=> Suggested changes to anonymous user selection

lib/cubits/tickets_page/tickets_cubit.dart, lib/cubits/tickets_page/tickets_state.dart, lib/data/repositories/v1/ticket_repository.dart, lib/widgets/components/coffee_card.dart, lib/widgets/components/tickets_section.dart
When a user swipes a ticket, it now uses a ticket in the backend, and displays a receipt
=> Users can swipe tickets

lib/base/strings.dart, lib/cubits/statistics/statistics_cubit.dart, lib/cubits/user/user_cubit.dart, lib/cubits/user/user_state.dart, lib/data/repositories/v1/account_repository.dart, lib/widgets/components/loading.dart, lib/widgets/components/settings_group.dart, lib/widgets/components/settings_list_entry.dart, lib/widgets/components/user_card.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/pages/settings/your_profile_page.dart
closes #162 
displays a switch on the settingspage allowing the logged in user to toggle their 'privacyActivated' field
@jonasanker does the backend omit people with this field set to 'true' or should it be handled in the frontend? I do believe it would be better to handle in the backend as we only receive names and scores from the API call. Thoughts?
=> add 'show me on leaderboard button' to settingspage

lib/widgets/pages/stats_page.dart
=> refresh user details on stats page refresh

lib/widgets/components/stats/leaderboard_list_view.dart
=> remove duplicate user from leaderboard

lib/base/strings.dart, lib/cubits/login/login_cubit.dart, lib/cubits/register/register_cubit.dart, lib/cubits/user/user_cubit.dart, lib/data/repositories/shared/account_repository.dart, lib/service_locator.dart, lib/utils/reactivation_authenticator.dart, lib/widgets/pages/home_page.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/routers/login_router.dart, lib/widgets/routers/register_flow.dart, openapi/coffeecard_api_v2.swagger.json
closes #72 
*API call to handle account deletion
*dialog to confirm account deletion
=> Add setting to delete a user's account

lib/widgets/components/settings_list_entry.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/pages/settings/your_profile_page.dart
Suggested change to PR #206
- Change behaviour of setting with switch
- Change styling on disabled setting
=> Remove disabled property in settings list entry

lib/widgets/components/settings_list_entry.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/pages/settings/your_profile_page.dart
=> remove opening hours from settings; add disabled option to SettingsListEntry

lib/base/strings.dart, lib/data/repositories/shared/account_repository.dart, lib/widgets/components/entry/login/login_cta.dart, lib/widgets/components/entry/register/email_body.dart, lib/widgets/pages/login/login_email_page.dart, lib/widgets/pages/login/login_passcode_page.dart, lib/widgets/pages/register/register_email_page.dart
closes #95 
* Users can now request a passcode reset
=> allow user to request passcode reset

lib/widgets/pages/login/login_page.dart
=> Hotfix: floating numpad

lib/cubits/environment/environment_cubit.dart, lib/data/repositories/v2/app_config_repository.dart, lib/models/environment.dart
Demonstrates the usage of the methods offered by the generated code to get enums from dynamic types, to actual enums i.e. the environmentTypeFromJson call.
=> Stronger typing on the environmentType

lib/widgets/components/card.dart, lib/widgets/components/receipt/receipt_card.dart, lib/widgets/components/stats/stat_card.dart, lib/widgets/components/tickets/buy_tickets_card.dart, lib/widgets/components/tickets/coffee_card.dart, lib/widgets/components/tickets/shop_card.dart, lib/widgets/components/tickets/shop_section.dart
closes #212 
* CardBase is no longer an abstract class
* Cards that previously inherited from CardBase, now returns an instance of it with appropriate styling
=> remove abstract modifier from CardBase

lib/widgets/components/tickets/coffee_card.dart
Fix #230, fix #151
When having more than 10 tickets, no longer shows extra counter.
=> Fix #230: Remove extra tickets counter

lib/cubits/purchase/purchase_cubit.dart, lib/models/purchase/payment.dart, lib/widgets/components/purchase/purchase_overlay.dart, lib/widgets/components/purchase/purchase_process.dart, lib/widgets/components/tickets/buy_ticket_bottom_modal_sheet.dart, lib/widgets/components/tickets/buy_tickets_card.dart
After a purchase, the user is now navigated back to the home_page if it was successful. Otherwise, they stay on the product page
=> Fix user send to home-page after purchase

lib/widgets/components/tickets/shop_section.dart, lib/widgets/pages/home_page.dart
=> Update tickets icon

lib/widgets/pages/home_page.dart
Current (top) vs proposed (bottom):
=> Update stats icon in nav bar

lib/data/repositories/v1/ticket_repository.dart
=> Sort owned tickets by their product id

lib/base/style/colors.dart, lib/widgets/components/stats/leaderboard_entry.dart
=> Replace leaderboard rank numbers with medal widget

lib/widgets/components/entry/register/name_body.dart, lib/widgets/components/forms/text_field.dart, lib/widgets/components/settings_list_entry.dart, lib/widgets/components/stats/leaderboard_entry.dart, lib/widgets/pages/settings/your_profile_page.dart
Fix #261 
Set max width of setting description
Enforce max length of 30 in name field
=> Fix leaderboard and setting entries overflowing

lib/widgets/components/user_card.dart, lib/widgets/pages/settings/settings_page.dart
Fix #136
Snapshot of loading screen (Log out button is still tappable):
=> Add shimmer loading effect to settings page

lib/base/strings.dart, lib/payment/mobilepay_service.dart, lib/payment/payment_handler.dart, lib/widgets/components/purchase/purchase_overlay.dart, lib/widgets/components/tickets/buy_ticket_bottom_modal_sheet.dart, lib/widgets/components/tickets/buy_tickets_card.dart, lib/widgets/components/tickets/shop_section.dart, lib/widgets/components/tickets/tickets_section.dart, lib/widgets/pages/tickets/buy_single_drink_page.dart
Closes #41 
Proof of concept for how the "buy single drink flow" can work with our current endpoints. 
The BuySingleDrinkPage is almost an exact copy of the BuyTicketsPage, so it does not adhere to the design spec, since I don't see a way to do so with our current data/ endpoints.
=> Buy single product

lib/widgets/components/receipt/receipt_overlay.dart, pubspec.lock, pubspec.yaml
=> adjust screen brightness on receipt display

lib/cubits/statistics/statistics_cubit.dart, lib/cubits/user/user_cubit.dart, lib/widgets/components/stats/leaderboard_entry.dart, lib/widgets/components/stats/leaderboard_list_view.dart, lib/widgets/components/stats/leaderboard_list_view_placeholder.dart, lib/widgets/components/stats/leaderboard_section.dart, lib/widgets/pages/stats_page.dart
=> Add shimmer loading effect to stats page

lib/widgets/pages/login/login_page_email.dart, lib/widgets/pages/tickets/buy_tickets_page.dart
=> buy_tickets_page reads cubits from context instead of service locator

lib/main.dart
=> Force screen orientation to portrait

lib/base/style/colors.dart, lib/widgets/components/receipt/receipt_card.dart, lib/widgets/pages/receipts/view_receipt_page.dart
IntrinsicHeight had no effect on ReceiptCard in ViewReceiptPage
- IntrinsicHeight replaced with Column
Remove unused color (highlight)
=> Fix receipt height; Adjust test env receipt color

lib/base/strings.dart, lib/cubits/opening_hours/opening_hours_cubit.dart, lib/cubits/opening_hours/opening_hours_state.dart, lib/data/repositories/shiftplanning/opening_hours_repository.dart, lib/widgets/pages/settings/opening_hours_page.dart, lib/widgets/pages/settings/settings_page.dart
=> settingspage displays opening hours

.github/workflows/firebase.yml, .github/workflows/flutter.yml
Fixing the last changes from #294
=> Bump Pipelines to Flutter v3.0.0

pubspec.lock, pubspec.yaml
Resolves annoying null binding errors on build
=> Bump animations package

lib/models/purchase/payment.dart, lib/payment/mobilepay_service.dart, lib/widgets/components/purchase/purchase_overlay.dart, lib/widgets/pages/tickets/buy_tickets_page.dart, openapi/coffeecard_api.swagger.json, openapi/coffeecard_api_v2.swagger.json
=> Update OpenApi specifications

lib/base/strings.dart, lib/data/api/coffee_card_api_constants.dart, lib/payment/mobilepay_service.dart, lib/payment/payment_handler.dart, lib/utils/launch.dart, lib/widgets/components/contributor_card.dart, lib/widgets/components/purchase/purchase_overlay.dart, lib/widgets/pages/settings/credits_page.dart, lib/widgets/pages/settings/settings_page.dart
=> Open Privacy Policy in external browser

lib/widgets/components/email_button_group.dart, lib/widgets/pages/login/forgot_passcode_page.dart
=> Do not check for duplicate email in forgot passcode flow

lib/widgets/pages/settings/settings_page.dart
=> sign user out when confirming account deletion

lib/cubits/environment/environment_cubit.dart, lib/cubits/environment/environment_state.dart, lib/models/environment.dart, lib/widgets/components/scaffold.dart, lib/widgets/components/tickets/tickets_section.dart, lib/widgets/pages/receipts/view_receipt_page.dart, lib/widgets/pages/tickets/buy_tickets_page.dart
Addresses
`TODO: handle potential other types better`
in `lib/cubits/environment/environment_cubit.dart`
=> refactor: generalize environment cubit loaded state

lib/cubits/environment/environment_cubit.dart, lib/cubits/environment/environment_state.dart, lib/models/environment.dart, lib/payment/mobilepay_service.dart, lib/widgets/components/scaffold.dart, lib/widgets/components/tickets/tickets_section.dart, lib/widgets/pages/receipts/view_receipt_page.dart, lib/widgets/pages/settings/settings_page.dart, lib/widgets/pages/tickets/buy_tickets_page.dart, lib/widgets/pages/tickets/redeem_voucher_page.dart
- Properly display redeemed vouchers in the tickets section (#341)
- Prepare app for MobilePay API changes (#338)
- Sign user out when requesting account deletion (#339)
- Generalize environment cubit loaded state (#305)
=> Release app (PATCH)

lib/widgets/components/stats/leaderboard_list_view.dart
=> user is no longer shown on leaderboard when not on top X

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner/Info.plist, lib/widgets/pages/settings/faq_page.dart
(misc) Update iOS build files
Replaced ExpansionTile with custom FAQ widget
Adjust padding sizes
=> Update FAQ page

lib/data/repositories/v2/purchase_repository.dart, lib/utils/time_since.dart, test/utils/time_since_test.dart
- Re-added paymentTypeToJson so dto can be deserialized (#371)
- Fix "in the future" when diff is very small (#372)
=> Release App (MINOR)

lib/base/strings.dart, lib/utils/time_since.dart, test/utils/time_since_test.dart
So many tests, and new code that passes the tests
=> Improve time since utility

lib/cubits/purchase/purchase_cubit.dart, lib/cubits/user/user_cubit.dart, lib/data/repositories/v1/ticket_repository.dart, lib/data/repositories/v2/purchase_repository.dart, lib/models/purchase/initiate_purchase.dart, lib/models/purchase/single_purchase.dart, lib/payment/mobilepay_service.dart, lib/payment/payment_handler.dart, lib/service_locator.dart, lib/utils/http_utils.dart, lib/widgets/components/purchase/purchase_process.dart, lib/widgets/components/receipt/receipt_list_entry.dart, lib/widgets/components/receipt/receipt_overlay.dart, lib/widgets/components/tickets/tickets_section.dart, lib/widgets/pages/tickets/buy_single_drink_page.dart, lib/widgets/routers/splash_router.dart
=> Remove todos

.github/workflows/build.yml
Prevented the pipeline from building iOS app for production
=> HOTFIX: Fix usage of `sed` command on MacOS

.github/workflows/build.yml
Primary purpose is to trigger a build on production branch
=> Small adjustment on build workflow

.env.develop, .env.production
We're going to Azure, babe 🔥 ‼️
=> Update Coffee Card API Server Urls

lib/features/ticket/presentation/pages/tickets_page.dart, lib/widgets/pages/settings/settings_page.dart
=> Disable showing opening hours

lib/features/ticket/presentation/widgets/swipe_ticket_confirm.dart
=> Added awaits for useTicket and FetchReceipts

lib/core/extensions/string_extensions.dart, test/core/extensions/string_extensions_test.dart
Now emoji-aware & empty-string aware!
Closes #470
=> test(utils): Improve String.capitalize() and add tests

test/features/product/domain/usecases/get_all_products_test.dart, test/features/product/presentation/cubit/product_cubit_test.dart
=> re-add product tests

.github/actions/build_android/action.yml, .github/workflows/build.yml
Building the Appbundle puts the artifact in a different folder compared to the APK
=> Fix Android appbundle path

README.md
=> Show Production release pipeline and correct test coverage in README

lib/features/contributor/data/datasources/contributor_local_data_source.dart
=> add Hubert as contributor

.github/workflows/codesee.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, .github/workflows/test.yml
=> build: add branch/PR info to dev release notes

.github/workflows/codesee.yml, .github/workflows/release-dev.yml, .github/workflows/release-prod.yml, .github/workflows/test.yml, lib/core/external/date_service.dart, lib/core/widgets/components/scaffold.dart, lib/features/opening_hours/data/datasources/opening_hours_local_data_source.dart, lib/features/opening_hours/data/repositories/opening_hours_repository_impl.dart, lib/features/opening_hours/domain/entities/opening_hours.dart, lib/features/opening_hours/domain/entities/timeslot.dart, lib/features/opening_hours/presentation/cubit/opening_hours_cubit.dart, lib/features/opening_hours/presentation/cubit/opening_hours_state.dart, lib/features/opening_hours/presentation/pages/opening_hours_page.dart, test/features/opening_hours/data/repositories/opening_hours_repository_impl_test.dart, test/features/opening_hours/domain/usecases/get_opening_hours_test.dart, test/features/opening_hours/presentation/cubit/opening_hours_cubit_test.dart
=> merge #546 #545 #541 into main

lib/features/ticket/presentation/widgets/swipe_ticket_confirm.dart
when swiping a ticket, skip menu item selection if a ticket can only claim one type of drink
=> feat(ticket): skip menu item selection

lib/features/occupation/presentation/widgets/occupation_form.dart, lib/features/settings/presentation/widgets/edit_profile.dart, lib/features/settings/presentation/widgets/settings_list_entry.dart
=> fix(ui): multi line text clipped in "select occupation" view
